Modified

diff --git a/ddns-start b/ddns-start
--- a/ddns-start
+++ b/ddns-start
@@ -8,27 +8,25 @@
 # 时间: 2016-02-24 16:25:00
 # Mod: 荒野无灯 http://ihacklog.com  2016-03-16
 # ReMod: 寒霜 https://www.frost.net.cn 2018-12-06
+# Remod(2): 无名萌新 2020-03-24
 #################################################
 
-# 使用Token认证(推荐) 请去 https://www.dnspod.cn/console/user/security 获取
+# 使用Token认证 请去 https://www.dnspod.cn/console/user/security 获取
 arToken="23745,b55b4692822de38a8d0955bc66bbfc5a"
-# 使用邮箱和密码认证
-arMail=""
-arPass=""
 
 # 获得外网ipv4地址
 arIpAdress() {
     local ipv4=$(ip addr show ppp0 | grep 'inet ')
-	local ipv4=${ipv4#*inet }
-	local ipv4=${ipv4% peer*}
+	ipv4=${ipv4#*inet }
+	ipv4=${ipv4% peer*}
 	echo ${ipv4}
 }
 
 # 获得外网ipv6地址
 arIpAdress_v6() {
     local ipv6=$(ip addr show br0 | grep 'inet6 [^f]')
-	local ipv6=${ipv6#*inet6 }
-	local ipv6=${ipv6%/*}
+	ipv6=${ipv6#*inet6 }
+	ipv6=${ipv6%/*}
 	echo ${ipv6}
 }
 
@@ -37,19 +35,20 @@ arIpAdress_v6() {
 arApiPost() {
     local agent="AnripDdns/5.07(mail@anrip.com)"
     local inter="https://dnsapi.cn/${1:?'Info.Version'}"
-    if [ "x${arToken}" = "x" ]; then # undefine token
-        local param="login_email=${arMail}&login_password=${arPass}&format=json&${2}"
+    local param="login_token=${arToken}&format=json&${2}"
+    local ret=$(wget --quiet --no-check-certificate --output-document=- --user-agent=$agent --post-data $param $inter)
+    if [ -z "$ret" ]; then
+        echo "wget error"
     else
-        local param="login_token=${arToken}&format=json&${2}"
+        echo $ret
     fi
-    wget --quiet --no-check-certificate --output-document=- --user-agent=$agent --post-data $param $inter
 }
 
 # 获得ID与初步数据
 getIDs() {
     domainID=$(arApiPost "Domain.Info" "domain=${domain}"|sed 's/.\+{"id":"\([0-9]\+\)".\+/\1/')
-    returnDatav4=$(arApiPost "Record.List" "domain_id=${domainID}&sub_domain=${sub_domain}&record_type=A")
-    returnDatav6=$(arApiPost "Record.List" "domain_id=${domainID}&sub_domain=${sub_domain}&record_type=AAAA")
+    returnDatav4=$(arApiPost "Record.List" "domain_id=${domainID}&sub_domain=${subdomainv4}")
+    returnDatav6=$(arApiPost "Record.List" "domain_id=${domainID}&sub_domain=${subdomainv6}")
 }
 
 # 查询域名地址
@@ -67,18 +66,21 @@ arNslookup_v6() {
 
 # 更新ipv4记录信息
 arDdnsUpdate() {
+    local hostIP=${1}
     local recordID recordRS recordCD
     # 获取记录ID
     recordID=$(echo $returnDatav4|sed 's/.\+\[{"id":"\([0-9]\+\)".\+/\1/')
     # 更新记录IP
-    recordRS=$(arApiPost "Record.Ddns" "domain_id=${domainID}&record_id=${recordID}&sub_domain=${sub_domain}&record_line=默认")
-    recordCD=$(echo $recordRS | sed 's/.\+{"code":"\([0-9]\+\)".\+/\1/')
+    recordRS=$(arApiPost "Record.Modify" "domain_id=${domainID}&record_id=${recordID}&sub_domain=${subdomainv4}&value=${hostIP}&record_type=A&record_line=默认")
+    recordCD=$(echo $recordRS | sed 's/.\+{"code":"\(\-\?[0-9]\+\)".\+/\1/')
     # 输出记录IP
     if [ "$recordCD" == "1" ]; then
-        echo $recordRS | sed 's/.\+,"value":"\([0-9\.]\+\)".\+/\1/'
+        echo "SUCCEESS"
+        echo $recordRS | sed 's/.\+"value":"\([0-9\.]\+\)".\+/\1/'
         return 0
     fi
     # 输出错误信息
+    echo "ERROR CODE: ${recordCD}"
     echo $recordRS | sed 's/.\+,"message":"\([^"]\+\)".\+/\1/'
     return 1
 }
@@ -89,16 +91,17 @@ arDdnsUpdate_v6() {
     local recordID recordRS recordCD
     recordID=$(echo $returnDatav6|sed 's/.\+\[{"id":"\([0-9]\+\)".\+/\1/')
     # 更新记录IP
-    recordRS=$(arApiPost "Record.Modify" "domain_id=${domainID}&record_id=${recordID}&sub_domain=${subdomain}&value=${hostIP_v6}&record_type=AAAA&record_line=默认")
-    recordCD=$(echo -E $recordRS | sed 's/.\+{"code":"\([0-9]\+\)".\+/\1/')
+    recordRS=$(arApiPost "Record.Modify" "domain_id=${domainID}&record_id=${recordID}&sub_domain=${subdomainv6}&value=${hostIP_v6}&record_type=AAAA&record_line=默认")
+    recordCD=$(echo -E $recordRS | sed 's/.\+"code":"\(\-\?[0-9]\+\)".\+/\1/')
     # 输出记录IP
     if [ "$recordCD" == "1" ]; then
-        echo "success"
+        echo "SUCCESS"
+        echo $recordRS | sed 's/.\+"value":"\([^"]\+\)".\+/\1/'
         return 0
     fi
     # 输出错误信息
-    echo $recordRS | sed 's/.\+,"code":"\([0-9\.]\+\)".\+/\1/'
-    echo $recordRS | sed 's/.\+,"message":"\([^"]\+\)".\+/\1/'
+    echo "ERROR CODE: ${recordCD}"
+    echo $recordRS | sed 's/.\+"message":"\([^"]\+\)".\+/\1/'
     return 1
 }
 
@@ -112,30 +115,29 @@ arDdnsCheck() {
     getIDs
 
     local postRS hostIP lastIP postRS_v6 hostIP_v6 lastIP_v6
+    local v4ok=0
+    local v6ok=0
 
     # ipv4
-    if [ -n "$subdomainv4" ]
-    then
+    if [ -n "$subdomainv4" ]; then
         hostIP=$(arIpAdress)
         echo "hostIP: ${hostIP}"
         lastIP=$(arNslookup)
         echo "lastIP: ${lastIP}"
 
         if [ "$lastIP" != "$hostIP" ]; then
-            arDdnsUpdate
+            arDdnsUpdate ${hostIP}
             if [ $? -ne 0 ]; then
-                /sbin/ddns_custom_updated 1
-            else
-                /sbin/ddns_custom_updated 0
+                v4ok=1
             fi
         else
-            /sbin/ddns_custom_updated 1
+            echo "SKIP"
+            v4ok=1
         fi
     fi
 
     # ipv6
-    if [ -n "subdomainv6" ]
-    then
+    if [ -n "subdomainv6" ]; then
         hostIP_v6=$(arIpAdress_v6)
         echo "hostIP_v6: ${hostIP_v6}"
         lastIP_v6=$(arNslookup_v6)
@@ -143,11 +145,24 @@ arDdnsCheck() {
 
         if [ "$lastIP_v6" != "$hostIP_v6" ]; then
             arDdnsUpdate_v6 ${hostIP_v6}
+            if [ $? -ne 0 ]; then
+                v6ok=1
+            fi
+        else
+            echo "SKIP"
+            v6ok=1
         fi
+    fi
+
+    if [ $v4ok -eq 1 -o $v6ok -eq 1 ]; then
+        /sbin/ddns_custom_updated 1
+    else
+        /sbin/ddns_custom_updated 0
     fi
 }
 
 ###################################################
 # 检查更新域名
 # 指定 domain subdomainv4 subdomaipv6
+# 不解析则不填，解析到主域名填@
 arDdnsCheck "frostfall.cn" "" ""
